project:
  type: website

website:
  title: "Crime-Aware Rideshare Optimization"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: data_exploration.ipynb
        text: Data Exploration
      - href: analysis.ipynb
        text: Analysis
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    toc-depth: 2



